// Planets
export const SELECT_PLANET = {
    ADD: 'SELECT_PLANET_ADD',
    REPLACE: 'SELECT_PLANET_REPLACE',
    RESET: 'SELECT_PLANET_RESET'
};

// Vehicles
export const SELECT_VEHICLE = {
    ADD: 'SELECT_VEHICLE_ADD',
    REPLACE: 'SELECT_VEHICLE_REPLACE',
    RESET: 'SELECT_VEHICLE_RESET'
};

export const FETCH_PLANETS = {
    BEGIN: "FETCH_PLANETS_BEGIN",
    SUCCESS: "FETCH_PLANETS_SUCCESS",
    FAILURE: "FETCH_PLANETS_FAILURE"
};

export const FETCH_VEHICLES = {
    BEGIN: "FETCH_VEHICLES_BEGIN",
    SUCCESS: "FETCH_VEHICLES_SUCCESS",
    FAILURE: "FETCH_VEHICLES_FAILURE"
};